version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "17 10 * * *"
    open-pull-requests-limit: 5
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
