apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - network-policies.yaml
configMapGenerator:
  - name: obsync-tls-proxy-config
    files:
      - nginx.conf
generatorOptions:
  immutable: true
